[general]
import = ["~/dotfiles/alacritty/alacritty-theme/themes/dracula.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control|Alt|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Equals"
mods = "Control|Alt"
