require('plugin-config/completion')
require('plugin-config/dap')
require('plugin-config/git')
require('plugin-config/lsp')
require('plugin-config/telescope')
require('plugin-config/treesitter')
require('plugin-config/misc')
